version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
    python: "mambaforge-4.10"

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: docs/source/env.yml

python:
  setup_py_install: true
