version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
    python: "mambaforge-4.10"

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: docs/source/env.yml

python:
  version: 3.6
  install:
    - method: setuptools
      path: .
