site_name: RNAvigate
site_url: https://rnavigate.readthedocs.io
nav:
- Home: index.md
- Getting started:
  - 'Installation': 'installing-rnavigate.md'
  - 'Loading data': 'loading-data.md'
  - 'Visualizing data': 'visualizing_data.ipynb'
- Plotting options:
  - 'Alignments': 'plot_options/alignment.ipynb'
  - 'Skylines': 'plot_options/skyline.ipynb'
  - 'Profiles': 'plot_options/profile.ipynb'
  - 'Arcs': 'plot_options/arc.ipynb'
  - 'Arcs comparison': 'plot_options/arc_compare.ipynb'
  - 'Circles': 'plot_options/circle.ipynb'
  - 'Secondary structures': 'plot_options/ss.ipynb'
  - 'Interactive 3D plots': 'plot_options/mol.ipynb'
  - 'Shapemapper2 QC': 'plot_options/qc.ipynb'
  - 'Shapemapper2 Profiles': 'plot_options/shapemapper.ipynb'
  - 'Distance distributions': 'plot_options/disthist.ipynb'
  - 'Heatmap and Contours': 'plot_options/heatmap.ipynb'
  - 'Linear regressions': 'plot_options/linreg.ipynb'
  - 'Receiver operator characteristic': 'plot_options/roc.ipynb'
- Analysis options:
  - 'Area under ROC curve': 'analysis-options/auroc.md'
  - 'DeltaSHAPE': 'analysis-options/deltashape.ipynb'
  - 'Log profile comparison': 'analysis-options/logcompare.md'
  - 'Low SHAPE, low Shannon entropy': 'analysis-options/lowss.md'
  - 'FragMapper': 'analysis-options/fragmapper.ipynb'
- Guides:
  - 'Interactions filtering': 'guides/filters.md'
  - 'Loading custom data': 'guides/loading-custom-data.md'
- General:
  - 'Glossary': 'glossary.md'
  - 'Publications': 'publications.md'
  - 'Code Reference': 'dev/full_api.md'
  - 'Change log': 'dev/changelog.md'

plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      kernel_name: Python3


theme: readthedocs
