site_name: RNAvigate
site_url: https://rnavigate.readthedocs.io
nav:
- Home: index.md
- Getting started:
  - 'Installation': 'installing-rnavigate.md'
  - 'Loading data': 'loading-data.md'
  - 'Visualizing data': 'visualizing-data.md'
  - 'Basic examples': 'examples/one_sample.ipynb'
- Plotting options:
  - 'Skyline plots': 'plot-options/skyline-plots.md'
  - 'Arc plots': 'plot-options/arc-plots.md'
  - 'Circle plots': 'plot-options/circle-plots.md'
  - 'Secondary structures': 'plot-options/ss-plots.md'
  - 'Interactive 3D plots': 'plot-options/mol-plots.md'
- Interactions filters:
  - 'Interactions reference': 'filters.md'
  - 'Interactions examples': 'examples/filtering.ipynb'
- Annotations:
  - 'Annotation reference': 'annotations.md'
  - 'Annotation examples': 'examples/annotations.ipynb'
- RNA 2022 Poster:
  - 'Poster': 'rna2022.md'
  - 'Time-resolved probing': 'poster/RNaseP/RNaseP.ipynb'
  - 'DANCE-MaP': 'poster/addRS/AddWT.ipynb'
  - 'Low SHAPE/Shannon entropy': 'poster/denv2/DENV2.ipynb'

plugins:
  - mkdocs-jupyter

theme: readthedocs
