site_name: RNAvigate
site_url: https://rnavigate.readthedocs.io
nav:
- Home: index.md
- Getting started:
  - 'Installation': 'installing-rnavigate.md'
  - 'Loading data': 'loading-data.md'
  - 'Visualizing data': 'visualizing-data.md'
  - 'Basic examples': 'examples/one_sample.ipynb'
- Plotting options:
  - 'Alignments': 'plot-options/alignment-plots.md'
  - 'Skylines': 'plot-options/skyline-plots.md'
  - 'Profiles': 'plot-options/profile-plots.md'
  - 'Arcs': 'plot-options/arc-plots.md'
  - 'Arcs comparison': 'plot-options/arc-compare-plots.md'
  - 'Circles': 'plot-options/circle-plots.md'
  - 'Secondary structures': 'plot-options/ss-plots.md'
  - 'Interactive 3D plots': 'plot-options/mol-plots.md'
  - 'Shapemapper2 QC': 'plot-options/qc-plots.md'
  - 'Shapemapper2 Profiles': 'plot-options/sm-plots.md'
  - 'Distance distributions': 'plot-options/disthist-plots.md'
  - 'Heatmap and Contours': 'plot-options/heatmap-plots.md'
  - 'Linear regressions': 'plot-options/linreg-plots.md'
  - 'Receiver operator characteristic': 'plot-options/roc-plots.md'
- Analysis options:
  - 'Area under ROC curve': 'analysis-options/auroc.md'
  - 'DeltaSHAPE': 'analysis-options/deltashape.md'
  - 'Log profile comparison': 'analysis-options/logcompare.md'
  - 'Low SHAPE, low Shannon entropy': 'analysis-options/lowss.md'
- Guides:
  - 'Interactions filtering': 'guides/filters.md'
  - 'Loading custom data': 'guides/loading-custom-data.md'
- Glossary: glossary.md
- Publications: publications.md
- Change log: changelog.md

plugins:
  - mkdocs-jupyter

theme: readthedocs
